### PR TITLE
Make it work with newer version of MacOS

### LINKED ISSUE #1: hanging on macOS
The library is hanging on macOS High Sierra (latest), after some debugging, [this message](https://github.com/bettercap/gatt/blob/master/device_darwin.go#L73) is correctly sent but no response is received [on this channel](https://github.com/bettercap/gatt/blob/master/device_darwin.go#L513), probably some of those XPC constants/structures/types changed.

idk ¯\\\_(ツ)\_/¯

### PR DESCRIPTION
**Pull request by raff**
This should fix https://github.com/bettercap/gatt/issues/1

### CODE REVIEW

**Comment by YugoCode** [comment]
Could this change please be merged? :)

**Comment by evilsocket** [comment]
sorry guys for the delay! @raff testing it, meanwhile: *thanks!*

**Comment by evilsocket** [comment]
@raff not working on Mojave 10.14.4 ... I see some entries, but their mac address is completely wrong and no advertising data is parsed

**Comment by raff** [comment]
@evilsocket, I don't have 10.14 anymore. Can you run this from my package https://github.com/raff/goble:

    go run examples/discoverer.go --verbose

**Comment by raff** [comment]
@evilsocket, I have also found that this wasn't working anymore with the latest 10.15 beta. Made a couple of fixes.

**Comment by evilsocket** [comment]
still not working :/

Schermata da 2019-09-10 12-49-19

**Pull request merged**
